# Generated by Django 5.1.7 on 2025-04-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorio',
        ),
    ]
